### ISSUE TITLE
Fix issue with flaky UI test "Stop AtlasMap and verify correct notification"

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#170]
```
Stop AtlasMap and verify correct notification
        1) Stop Command should show a notification with the correct text
        2) "after each" hook for "Stop Command should show a notification with the correct text"
```

```
 1) AtlasMap UI tests
       Start AtlasMap and verify correct notifications
         Stop AtlasMap and verify correct notification
           Stop Command should show a notification with the correct text:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/all.js)
  
  2) AtlasMap UI tests
       Start AtlasMap and verify correct notifications
         "after each" hook for "Stop Command should show a notification with the correct text":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/all.js)
  
  3) "after all" hook in "{root}":
     Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  
/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/promise.js:2626
        throw error;
        ^
WebDriverError: no such session
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-1028-gcp x86_64)
    at Object.checkLegacyResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebElement.findElement(By(css selector, .monaco-workbench))
    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at WebElementPromise.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
    at WebElementPromise.findElement (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
    at new AbstractElement (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/AbstractElement.js:42:48)
    at new Workbench (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/Workbench.js:27:9)
    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:37:34)
    at Generator.next (<anonymous>)
    at /home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:4:12)
```

**Comment by apupier** [comment]
@jkopriva @djelinek Can you have a look please?

**Comment by jkopriva** [comment]
closing, this was fixed by https://github.com/jboss-fuse/vscode-atlasmap/pull/174
