### ISSUE TITLE
Fix issue with lot of "rejected promise not handled within 1 second: Error: Channel has been closed" logged

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#171]
```
  ✓ Test import of ADM file with stopped server: 14059ms
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
rejected promise not handled within 1 second: Error: Channel has been closed
stack trace: Error: Channel has been closed
    at p.validate (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:885)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:578:440)
    at p.append (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:276)
    at define.append._channel.then.t (/home/travis/build/jboss-fuse/vscode-atlasmap/.vscode-test/vscode-1.38.0/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:579:485)
Error: connect ECONNREFUSED 127.0.0.1:8585
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
      1) Test import of ADM file with running server
```

**Comment by apupier** [comment]
it might be the same issues than https://github.com/jboss-fuse/vscode-atlasmap/issues/112 with the difference that a newer version of VS Code is reporting more errors
