### ISSUE TITLE
UI Tests are failing on startup

### ISSUE THREAD

**Issue by djelinek** [jboss-fuse/vscode-atlasmap#208]
This issue is related to new changes inside vscode-extension-tester.

Fix:
"test-resources" folder must be added into ".vscodeignore" file

```
This extension consists of 1709 separate files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/mnt/hudson_workspace/workspace/vscode_atlasmap_pipeline/vscode-atlasmap/test-resources/chromedriver'
Emitted 'error' event at:
    at ReadStream.<anonymous> (/mnt/hudson_workspace/workspace/vscode_atlasmap_pipeline/vscode-atlasmap/node_modules/yazl/index.js:39:14)
    at ReadStream.emit (events.js:203:13)
    at internal/fs/streams.js:123:12
    at FSReqCallback.oncomplete (fs.js:153:23) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/mnt/hudson_workspace/workspace/vscode_atlasmap_pipeline/vscode-atlasmap/test-resources/chromedriver'
}
(node:6559) UnhandledPromiseRejectionWarning: Error: Command failed: vsce package
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at CodeUtil.packageExtension (/mnt/hudson_workspace/workspace/vscode_atlasmap_pipeline/vscode-atlasmap/node_modules/vscode-extension-tester/out/util/codeUtil.js:122:23)
    at ExTester.installVsix (/mnt/hudson_workspace/workspace/vscode_atlasmap_pipeline/vscode-atlasmap/node_modules/vscode-extension-tester/out/extester.js:82:23)
    at ExTester.<anonymous> (/mnt/hudson_workspace/workspace/vscode_atlasmap_pipeline/vscode-atlasmap/node_modules/vscode-extension-tester/out/extester.js:113:18)
    at Generator.next (<anonymous>)
    at fulfilled (/mnt/hudson_workspace/workspace/vscode_atlasmap_pipeline/vscode-atlasmap/node_modules/vscode-extension-tester/out/extester.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by djelinek** [comment]
merged and verified with master branch
