### ISSUE TITLE
UI tests are failing in Travis builds

### ISSUE THREAD

**Issue by djelinek** [jboss-fuse/vscode-atlasmap#212]
UI tests are failing in travis builds, but results are still green.

For more info please see Travis build logs.

@jkopriva could you please take a look?

```
Writing code settings to /home/travis/build/jboss-fuse/vscode-atlasmap/test-resources/settings/User/settings.json
466  AtlasMap UI tests
467    Start/Stop AtlasMap and verify correct notifications
468{ NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".clear-all-notifications-action"}
469  (Session info: chrome=69.0.3497.128)
470  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-1028-gcp x86_64)
471    at Object.checkLegacyResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/error.js:546:15)
472    at parseHttpResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:509:13)
473    at doSend.then.response (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:441:30)
474    at process._tickCallback (internal/process/next_tick.js:68:7)
475From: Task: WebElement.findElement(By(css selector, .clear-all-notifications-action))
476    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
477    at NotificationsCenter.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
478    at NotificationsCenter.findElement (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
479    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:24)
480    at Generator.next (<anonymous>)
481    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
482    at new Promise (<anonymous>)
483    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
484    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
485    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26)
486From: Task: WebElement.click()
487    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
488    at WebElementPromise.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
489    at WebElementPromise.click (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
490    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:92)
491    at Generator.next (<anonymous>)
492    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
493    at new Promise (<anonymous>)
494    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
495    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
496    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26) name: 'NoSuchElementError', remoteStacktrace: '' }
497      ✓ Start Command should show a notification with the correct text (22041ms)
498{ NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".clear-all-notifications-action"}
499  (Session info: chrome=69.0.3497.128)
500  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-1028-gcp x86_64)
501    at Object.checkLegacyResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/error.js:546:15)
502    at parseHttpResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:509:13)
503    at doSend.then.response (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:441:30)
504    at process._tickCallback (internal/process/next_tick.js:68:7)
505From: Task: WebElement.findElement(By(css selector, .clear-all-notifications-action))
506    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
507    at NotificationsCenter.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
508    at NotificationsCenter.findElement (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
509    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:24)
510    at Generator.next (<anonymous>)
511    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
512    at new Promise (<anonymous>)
513    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
514    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
515    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26)
516From: Task: WebElement.click()
517    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
518    at WebElementPromise.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
519    at WebElementPromise.click (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
520    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:92)
521    at Generator.next (<anonymous>)
522    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
523    at new Promise (<anonymous>)
524    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
525    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
526    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26) name: 'NoSuchElementError', remoteStacktrace: '' }
527{ NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".clear-all-notifications-action"}
528  (Session info: chrome=69.0.3497.128)
529  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-1028-gcp x86_64)
530    at Object.checkLegacyResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/error.js:546:15)
531    at parseHttpResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:509:13)
532    at doSend.then.response (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:441:30)
533    at process._tickCallback (internal/process/next_tick.js:68:7)
534From: Task: WebElement.findElement(By(css selector, .clear-all-notifications-action))
535    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
536    at NotificationsCenter.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
537    at NotificationsCenter.findElement (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
538    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:24)
539    at Generator.next (<anonymous>)
540    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
541    at new Promise (<anonymous>)
542    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
543    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
544    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26)
545From: Task: WebElement.click()
546    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
547    at WebElementPromise.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
548    at WebElementPromise.click (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
549    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:92)
550    at Generator.next (<anonymous>)
551    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
552    at new Promise (<anonymous>)
553    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
554    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
555    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26) name: 'NoSuchElementError', remoteStacktrace: '' }
556      ✓ Second Start Command should open AtlasMap window (1198ms)
557{ NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".clear-all-notifications-action"}
558  (Session info: chrome=69.0.3497.128)
559  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-1028-gcp x86_64)
560    at Object.checkLegacyResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/error.js:546:15)
561    at parseHttpResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:509:13)
562    at doSend.then.response (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:441:30)
563    at process._tickCallback (internal/process/next_tick.js:68:7)
564From: Task: WebElement.findElement(By(css selector, .clear-all-notifications-action))
565    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
566    at NotificationsCenter.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
567    at NotificationsCenter.findElement (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
568    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:24)
569    at Generator.next (<anonymous>)
570    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
571    at new Promise (<anonymous>)
572    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
573    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
574    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26)
575From: Task: WebElement.click()
576    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
577    at WebElementPromise.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
578    at WebElementPromise.click (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
579    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:92)
580    at Generator.next (<anonymous>)
581    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
582    at new Promise (<anonymous>)
583    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
584    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
585    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26) name: 'NoSuchElementError', remoteStacktrace: '' }
586{ NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".clear-all-notifications-action"}
587  (Session info: chrome=69.0.3497.128)
588  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-1028-gcp x86_64)
589    at Object.checkLegacyResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/error.js:546:15)
590    at parseHttpResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:509:13)
591    at doSend.then.response (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:441:30)
592    at process._tickCallback (internal/process/next_tick.js:68:7)
593From: Task: WebElement.findElement(By(css selector, .clear-all-notifications-action))
594    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
595    at NotificationsCenter.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
596    at NotificationsCenter.findElement (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
597    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:24)
598    at Generator.next (<anonymous>)
599    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
600    at new Promise (<anonymous>)
601    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
602    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
603    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26)
604From: Task: WebElement.click()
605    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
606    at WebElementPromise.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
607    at WebElementPromise.click (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
608    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:92)
609    at Generator.next (<anonymous>)
610    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
611    at new Promise (<anonymous>)
612    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
613    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
614    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26) name: 'NoSuchElementError', remoteStacktrace: '' }
615      ✓ Stop Command should show a notification with the correct text (4194ms)
616{ NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".clear-all-notifications-action"}
617  (Session info: chrome=69.0.3497.128)
618  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-1028-gcp x86_64)
619    at Object.checkLegacyResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/error.js:546:15)
620    at parseHttpResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:509:13)
621    at doSend.then.response (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:441:30)
622    at process._tickCallback (internal/process/next_tick.js:68:7)
623From: Task: WebElement.findElement(By(css selector, .clear-all-notifications-action))
624    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
625    at NotificationsCenter.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
626    at NotificationsCenter.findElement (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
627    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:24)
628    at Generator.next (<anonymous>)
629    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
630    at new Promise (<anonymous>)
631    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
632    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
633    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26)
634From: Task: WebElement.click()
635    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
636    at WebElementPromise.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
637    at WebElementPromise.click (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
638    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:92)
639    at Generator.next (<anonymous>)
640    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
641    at new Promise (<anonymous>)
642    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
643    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
644    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26) name: 'NoSuchElementError', remoteStacktrace: '' }
645{ NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".clear-all-notifications-action"}
646  (Session info: chrome=69.0.3497.128)
647  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-1028-gcp x86_64)
648    at Object.checkLegacyResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/error.js:546:15)
649    at parseHttpResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:509:13)
650    at doSend.then.response (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:441:30)
651    at process._tickCallback (internal/process/next_tick.js:68:7)
652From: Task: WebElement.findElement(By(css selector, .clear-all-notifications-action))
653    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
654    at NotificationsCenter.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
655    at NotificationsCenter.findElement (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
656    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:24)
657    at Generator.next (<anonymous>)
658    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
659    at new Promise (<anonymous>)
660    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
661    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
662    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26)
663From: Task: WebElement.click()
664    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
665    at WebElementPromise.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
666    at WebElementPromise.click (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
667    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:92)
668    at Generator.next (<anonymous>)
669    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
670    at new Promise (<anonymous>)
671    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
672    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
673    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26) name: 'NoSuchElementError', remoteStacktrace: '' }
674      ✓ Second Stop Command should show a notification with the correct text (1118ms)
675{ NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".clear-all-notifications-action"}
676  (Session info: chrome=69.0.3497.128)
677  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-1028-gcp x86_64)
678    at Object.checkLegacyResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/error.js:546:15)
679    at parseHttpResponse (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:509:13)
680    at doSend.then.response (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/http.js:441:30)
681    at process._tickCallback (internal/process/next_tick.js:68:7)
682From: Task: WebElement.findElement(By(css selector, .clear-all-notifications-action))
683    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
684    at NotificationsCenter.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
685    at NotificationsCenter.findElement (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
686    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:24)
687    at Generator.next (<anonymous>)
688    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
689    at new Promise (<anonymous>)
690    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
691    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
692    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26)
693From: Task: WebElement.click()
694    at Driver.schedule (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
695    at WebElementPromise.schedule_ (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
696    at WebElementPromise.click (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
697    at NotificationsCenter.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:39:92)
698    at Generator.next (<anonymous>)
699    at /home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:8:71
700    at new Promise (<anonymous>)
701    at __awaiter (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:4:12)
702    at NotificationsCenter.clearAllNotifications (/home/travis/build/jboss-fuse/vscode-atlasmap/node_modules/vscode-extension-tester/out/webdriver/components/workbench/NotificationsCenter.js:38:16)
703    at Object.<anonymous> (/home/travis/build/jboss-fuse/vscode-atlasmap/out/ui-test/common/utils.js:36:26) name: 'NoSuchElementError', remoteStacktrace: '' }
```

**Comment by djelinek** [comment]
closing - verified
