### ISSUE TITLE
The GUI/Editor Window does not open on Create Atlasmap command

### ISSUE THREAD

**Issue by geojaya** [jboss-fuse/vscode-atlasmap#893]
I have Windows 10 enterprise . When I run the  Create Atlasmap  file command, from the command Paltte in VS Code, nothing happens. I  tried with Java 8 and Java 11 on JAVA_HOME Path variable

**Comment by apupier** [comment]
Can you precise the version of VS Code AtlasMap (visible from the Extension panel), the version of VS Code (Help -> About) please?

Do you have errors in one of these outputs (View -> Output):
- Log (Shared)
- Log (Window)
- Log (Main)
- AtlasMap Server for XXX

is the file created in the workspace?
Does the UI is displayed if you create an empty file called xxx.adm and try to open it?

have you configured the settings java.home in VS Code?

**Comment by geojaya** [comment]
Using VS Code Version 1.71.2
Atlas Map version  v0.2.2

I see nothing in the output

JAVA_HOME is defined and it is JAVA  8

If I try to open an .adm file, VS Code  will say a message - waiting for editors to open ATlasMap GUI for the file, later it will say 'failed to resolve Atlas Map  web UI

**Comment by geojaya** [comment]
There is output logging
:: Spring Boot ::               (v2.5.12)

2022-09-27 05:53:05.913  INFO 28356 --- [           main] io.atlasmap.standalone.Application       : Starting Application using Java 17.0.1 on IT-WS27 with PID 28356 (C:\Users\testusergv\.vscode\extensions\redhat.atlasmap-viewer-0.2.2\jars\atlasmap-standalone.jar started by testusergv in C:\Users\testusergv\AppData\Local\Programs\Microsoft VS Code)
2022-09-27 05:53:05.916  INFO 28356 --- [           main] io.atlasmap.standalone.Application       : No active profile set, falling back to 1 default profile: "default"
2022-09-27 05:53:07.609  INFO 28356 --- [           main] j.r.s.ResteasyEmbeddedServletInitializer : Finding JAX-RS Application classes
2022-09-27 05:53:07.614  INFO 28356 --- [           main] j.r.s.ResteasyEmbeddedServletInitializer : Property resteasy.jaxrs.app.registration has been set to beans
2022-09-27 05:53:07.617  INFO 28356 --- [           main] j.r.s.ResteasyEmbeddedServletInitializer : Searching for JAX-RS Application Spring beans
2022-09-27 05:53:07.620  INFO 28356 --- [           main] j.r.s.ResteasyEmbeddedServletInitializer : JAX-RS Application class found: io.atlasmap.standalone.JaxrsApplication
2022-09-27 05:53:08.311  WARN 28356 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-09-27 05:53:08.366  INFO 28356 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2022-09-27 05:53:08.366  INFO 28356 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2380 ms
2022-09-27 05:53:09.430  WARN 28356 --- [           main] .s.s.UserDetailsServiceAutoConfiguration : 

Using generated security password: 979cc001-b239-4d87-b635-ff4f039ef7de

This generated password is for development use only. Your security configuration must be updated before running your application in production.

2022-09-27 05:53:09.577  INFO 28356 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure any request
2022-09-27 05:53:10.191  WARN 28356 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'atlasService' defined in class path resource [io/atlasmap/standalone/JaxrsApplication.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.atlasmap.service.AtlasService]: Factory method 'atlasService' threw exception; nested exception is io.atlasmap.api.AtlasException: 'lib' is not a directory
2022-09-27 05:53:10.211  INFO 28356 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-09-27 05:53:10.252 ERROR 28356 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'atlasService' defined in class path resource [io/atlasmap/standalone/JaxrsApplication.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.atlasmap.service.AtlasService]: Factory method 'atlasService' threw exception; nested exception is io.atlasmap.api.AtlasException: 'lib' is not a directory
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.18.jar!/:5.3.18]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486) ~[spring-beans-5.3.18.jar!/:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.18.jar!/:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.18.jar!/:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.18.jar!/:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.18.jar!/:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.18.jar!/:5.3.18]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.18.jar!/:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.18.jar!/:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.18.jar!/:5.3.18]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.18.jar!/:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.18.jar!/:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.18.jar!/:5.3.18]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.12.jar!/:2.5.12]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.5.12.jar!/:2.5.12]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:448) ~[spring-boot-2.5.12.jar!/:2.5.12]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) ~[spring-boot-2.5.12.jar!/:2.5.12]
	at io.atlasmap.standalone.Application.main(Application.java:34) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[atlasmap-standalone.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[atlasmap-standalone.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[atlasmap-standalone.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[atlasmap-standalone.jar:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.atlasmap.service.AtlasService]: Factory method 'atlasService' threw exception; nested exception is io.atlasmap.api.AtlasException: 'lib' is not a directory
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.18.jar!/:5.3.18]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.18.jar!/:5.3.18]
	... 25 common frames omitted
Caused by: io.atlasmap.api.AtlasException: 'lib' is not a directory
	at io.atlasmap.service.AtlasLibraryLoader.<init>(AtlasLibraryLoader.java:62) ~[atlas-service-2.5.0.jar!/:2.5.0]
	at io.atlasmap.service.AtlasService.<init>(AtlasService.java:108) ~[atlas-service-2.5.0.jar!/:2.5.0]
	at io.atlasmap.standalone.JaxrsApplication.atlasService(JaxrsApplication.java:61) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.18.jar!/:5.3.18]
	... 26 common frames omitted

**Comment by apupier** [comment]
Given `c:\Users\testusergv\AppData\Roaming\Code\User\workspaceStorage\2f77de43de4ede1f248dc8724f7cee97\redhat.atlasmap-viewer\.atlasmap\c:\Users\testusergv\Downloads\monkey\atlas1.adm'`, it seems that the path is not resolved correctly as there is he concatenation of 2 absolute path

**Comment by apupier** [comment]
another point is that it is started using Java 17: `Starting Application using Java 17.0.1`

**Comment by geojaya** [comment]
does it support java 17

**Comment by apupier** [comment]
> does it support java 17

not sure. Seems AtlasMap 2.5.x which is embedded in VS Code AtlasMap was tested with Java 8 and 11 only: https://github.com/atlasmap/atlasmap/blob/540962b94d366f975cf7cb8e97dfc743dd169e76/.github/workflows/supported-build.yml#L19

**Comment by geojaya** [comment]
I changed to Java 11 and still getting same error

**Comment by geojaya** [comment]
Not sure - why it has to concatenate two absolute path -

**Comment by geojaya** [comment]
The  .adm file is located in c:\Users\testusergv\Downloads\monkey\

**Comment by geojaya** [comment]
issue resolved, 
added a folder to the work space, created .adm file in that folder and  opened in vs code and was able to able to open  the atlas  mapper
thanks for all your help

**Comment by geojaya** [comment]
closing  the issue

**Comment by apupier** [comment]
I was able to reproduce the initial issue and reported https://issues.redhat.com/browse/FUSETOOLS2-1857

For the other errors, I do not reproduce. I'm glad that you found a way to have it working for you.

thank you very much for the report and all the details provided.
